language: go
go:
- 1.15.x

before_script:
  - sudo apt-get install zip
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip -d /usr/local/bin/
  - update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force
  
addons:
  apt:
    update: true

script:
  - ./pre-commit
  - cd build
  - go build ./cmd/bood
  - bood
  - cd ../examples
  - go build ../build/cmd/bood
  - bood