language: go
go:
- 1.15.x

before_script:
  - sudo apt-get -y install ninja-build
  - sudo apt-get -y upgrade ninja-build
  - sudo apt-get install zip

addons:
  apt:
    update: true

script:
  - ./pre-commit
  - cd build
  - go build ./cmd/bood
  - bood
  - cd ../examples
  - go build ../build/cmd/bood
  - bood